### ISSUE TITLE
how to push changes even if any branch pretection rule applied on branch?

### ISSUE THREAD

**Issue by sriedjx** [fjogeleit/yaml-update-action#241]
I'm using this action to push the changes to same branch. but there is protection rule applied on that branch as `Require pull request reviews before merging`. but i need to push the changes with current action. is there any way to overcome this rule?  or any alternatives?

**Comment by fjogeleit** [comment]
Hey, thanks for your request. So you commit and push your change in the the branch and it doesn't work because of your proection rule? I wil check the REST API if I find something to handle this behavior.

**Comment by sriedjx** [comment]
one doubt, same action running through `repository_dispatch` event and its pushing(`41898282+github-actions[bot]@users.noreply.github.com` author) without any blocker. and this job is running through manual trigger but getting issue. why?

**Comment by fjogeleit** [comment]
Do you have a minimal example workflow? That I can reproduce your problem?

**Comment by sriedjx** [comment]
working 
```
name: update Manifest file
on:
  repository_dispatch:
     types: [Manifest]
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set edjx versions on development environment
        if: github.event_name == 'repository_dispatch'
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'conf/edjx/${{ github.event.client_payload.env }}.yaml'
          propertyPath: '${{ github.event.client_payload.repo }}'
          value: '${{ github.event.client_payload.version }}'
          branch: development
          targetBranch: development
          message: 'Update ${{ github.event.client_payload.repo }} Version to ${{ github.event.client_payload.version }}' 
          commitChange: true
```
not working
```
name: Triggered development environment
on:
  workflow_dispatch:  
    inputs:   
      name:
        description: 'Trigger build Manually'
        required: true
        default: 'build trigger'
  push:
   tags: 
    - v*
jobs:
 set_environment:
      - name: Update environment
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: '${{ needs.set_environment.outputs.env }}.yaml'
          propertyPath: 'version'
          value: '${{ needs.set_environment.outputs.version }}'
          branch: development
          targetBranch: development
          message: 'TRIGGERED_LOAD_ENV' 
          commitChange: true
```
