### ISSUE TITLE
YAMLException: unknown tag

### ISSUE THREAD

**Issue by ZsharE** [fjogeleit/yaml-update-action#245]
Hi,

I get an error when i try to edit my yaml file. That line works fine, it's an extension for MkDocs.

`Error: YAMLException: unknown tag !<tag:yaml.org,2002:python/name:pymdownx.emoji.to_svg> (17:5)`

```
markdown_extensions:
    - markdown_fenced_code_tabs:
        template: "bootstrap4"
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg   <---
    - attr_list
    - md_in_html
```

**Comment by fjogeleit** [comment]
Hey, thank you for reporting. I will have a look on your exception.

**Comment by fjogeleit** [comment]
Is it possible for you to set your value in quotes?

```yaml
markdown_extensions:
    - markdown_fenced_code_tabs:
        template: "bootstrap4"
    - pymdownx.emoji:
        emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
    - attr_list
    - md_in_html
```
