### ISSUE TITLE
Error: HttpError: Not Found

### ISSUE THREAD

**Issue by gboie** [fjogeleit/yaml-update-action#392]
I am getting this error when trying to use it...
(node:1615) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by fjogeleit** [comment]
Hey, are you change the file of another repository? Then be sure that the github token has permissions to access and commit to this repository

**Comment by gboie** [comment]
Hi @fjogeleit , it is in the same repository. Thank you

**Comment by fjogeleit** [comment]
Do you have some sort of protection rules against the branch you are changing? Can you provide some example how you use the action?

**Comment by tslavik** [comment]
I had the same issue. @gboie Try to specify organization name like "repository: org/repo". It works for me.

**Comment by tomfriedhof** [comment]
Thanks @tslavik that worked for me as well!

**Comment by pedrojreis** [comment]
Hello!

I'm having this exact same error and maybe you guys might be able to point me in the right direction.
I've created a token and authorized it to access my organization via SSO Configuration.

My step looks like this
```
      - name: Update deploy.yaml 📄
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: '.github/workflows/dev/k8s/30-application.yaml'
          propertyPath: 'spec.template.spec.containers.0.image'
          value: ${{  needs.build.outputs.image }}
          repository: organization/RepositoryName
          branch: ${{ needs.build.outputs.branch }}
          targetBranch: ${{ needs.build.outputs.branch }}
          updateFile: true
          createPR: false
          commitChange: true
          message: 'Update Image to 1.0.1' #To replace later
          token: ${{ secrets.TOKEN_GITHUB }}
```

And I get this output

```
(node:1580) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: HttpError: Not Found
```
