### ISSUE TITLE
key set to true results in 'true'

### ISSUE THREAD

**Issue by makakken** [fjogeleit/yaml-update-action#497]
```
- name: 🏕️ Set Environment to production
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'knotentheme.yaml'
          propertyPath: 'production'
          value: true
          commitChange: false
          updateFile: true
```

this results in 

`production: 'true'`

is it possible to change it to 

`production: true`

**???**

i dont need the single quotes.
