### ISSUE TITLE
httperror

### ISSUE THREAD

**Issue by abvijaykumar** [fjogeleit/yaml-update-action#501]
HI I am getting HTTPerror when I try to execute this block. What is wrong with this?

      - name: Update Image Version in the yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev/deployment-manifests/book-info-service-deployment.yaml'
          propertyPath: 'spec.template.spec.containers[1].image'
          value: 'abvijaykumar/bozo-book-info-service:${{github.event.client_payload.buildnumber}}'
          message: 'Update Image Version to abvijaykumar/bozo-book-info-service:${{github.event.client_payload.buildnumber}} '

**Comment by abvijaykumar** [comment]
Here is what I see on the github actions 

Run fjogeleit/yaml-update-action@main
  with:
    valueFile: dev/deployment-manifests/book-info-service-deployment.yaml
    propertyPath: spec.template.spec.containers[1].image
    value: abvijaykumar/bozo-book-info-service:[4](https://github.com/abvijaykumar/book-library-kube-infra/runs/8086460503?check_suite_focus=true#step:4:4)[6](https://github.com/abvijaykumar/book-library-kube-infra/runs/8086460503?check_suite_focus=true#step:4:6)
    message: Update Image Version to abvijaykumar/bozo-book-info-service:46 
    branch: master
    masterBranchName: master
    targetBranch: master
    githubAPI: https://api.github.com/
    createPR: false
    commitChange: true
    updateFile: false
    labels: yaml-updates
    token: ***
    repository: abvijaykumar/book-library-kube-infra
    workDir: .
    commitUserName: GitHub Actions
    commitUserEmail: actions@github.com
Error: HttpError: Not Found

**Comment by fjogeleit** [comment]
You pushing in the same repository as your source repository? Is it protected some how?

Depending on your configuration its maybe needed to create a GitHub Token for the action because the default one does not have the permissions to push.

So, I would recommend to create a custom GitHub token and use it instead of the default one.

**Comment by abvijaykumar** [comment]
Thanks for the response. Yes I am updating a file in the same repo. Let me try the token.

**Comment by abvijaykumar** [comment]
Hi - I update my code to pass toke, still I am getting the same error.

**Comment by abvijaykumar** [comment]
- name: Update Image Version in the yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev/deployment-manifests/book-info-service-deployment.yaml'
          propertyPath: 'spec.template.spec.containers[1].image'
          value: 'abvijaykumar/bozo-book-info-service:${{github.event.client_payload.buildnumber}}'
          token: ${{secrets.API_TOKEN_GITHUB}}
          message: 'Update Image Version to abvijaykumar/bozo-book-info-service:${{github.event.client_payload.buildnumber}} '

**Comment by fjogeleit** [comment]
Your default branch is `main`, right? Because of compatibility reasons the default branch of the action is `master`. You can configure it by using the `masterBranchName` property.

**Comment by abvijaykumar** [comment]
yes I just tried that, still I am getting the same error :-D I am sorry to bother u

**Comment by fjogeleit** [comment]
Can you please also set the `branch` to `main`? This is the actual branch where it tries to commit.

No worries, this action can be a bit hard to configure, depending on the individual needs. Glad to help with it.

**Comment by abvijaykumar** [comment]
Hi. I already tried branch and targetBranch. Gave both the values to main. Still it doesn't seem to work. Just to make sure, can you give me an example. I am using single quotes. Is that right ?

**Comment by fjogeleit** [comment]
```yaml
      - name: Update Chart Values
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'fints-service/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.tags.outputs.version }}
          repository: 'betreu-platform/charts'
          token: ${{ secrets.CHART_TOKEN }}
          masterBranchName: main
          branch: main
          createPR: 'false'
          message: 'Update Image Version to ${{ steps.tags.outputs.version }}'
          workDir: infrastructure
```

thats an example from one of my projects. Quotes should not matter

**Comment by fjogeleit** [comment]
I created a fork and check something

**Comment by fjogeleit** [comment]
So my fork is working as expected. 

```yaml
      - name: Update Image Version in the yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev/deployment-manifests/book-info-service-deployment.yaml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: 'abvijaykumar/bozo-book-info-service:${{ inputs.number }}'
          masterBranchName: 'main'
          branch: 'main'
          message: 'Update Image Version to abvijaykumar/bozo-book-info-service:${{ inputs.number }}' 
```

https://github.com/fjogeleit/book-library-kube-infra

Have you tried to remove your custom token after changing the branch and masterBranchName? Maybe there is an issue with the token. When the default token also fail, the last thing which comes to my mind is to try a new token with all available permissions, to check if its an permission issue at all.

And a small hint, the index of your propertyPath is wrong. It starts with `0` instead of `1`
