### ISSUE TITLE
YAMLException: expected a single document in the stream, but found more

### ISSUE THREAD

**Issue by 123MwanjeMike** [fjogeleit/yaml-update-action#516]
When I try to update a yaml file with a of documents, I get the message;

>  Error: YAMLException: expected a single document in the stream, but found more

The content of my `manifests.yaml` file is something similar to this;
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-name
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app-name
          image: image-repository/app-name:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: app-svc
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31104
  type: NodePort
```

Is there a work around this or I must separate the two into individual files so that I can update each?
