### ISSUE TITLE
Multi document file update: YAMLException: expected a single document in the stream, but found more

### ISSUE THREAD

**Issue by SVynnytska** [fjogeleit/yaml-update-action#532]
During update of a file with 3 documents inside received an error `YAMLException: expected a single document in the stream, but found more`. Does the action support multi documents files update 
```
      with:
        valueFile: "deploy/${{ env.ENVIRONMENT }}/values.yaml"
        propertyPath: "spec.template.spec.containers[0].env[0].value"
        value: ${{ inputs.version }}
        title: 'Version Updates '
        commitChange: true
        message: "build: automatic update - versions  to ${{ inputs.version }}"
        branch: ${{ inputs.branch_name }}
        token: ${{ inputs.github_token }}
        createPR: false
        commitUserName: bot
```

**Comment by fjogeleit** [comment]
Currently a YAML file with multiple documents splitted by `---` are not suppported. You would need to split the documents into separated files to get it working.

Example File:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: blog
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: secret
  namespace: blog
data: {}
```

into:

namespace.yaml
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: blog
```

secret.yaml
```yaml
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: ghcr
  namespace: blog
data: {}
```
