### ISSUE TITLE
Error: HttpError: Reference already exists

### ISSUE THREAD

**Issue by 123MwanjeMike** [fjogeleit/yaml-update-action#533]
I am running this action in a an environment with many jobs running in parallel on GitHub actions but at least 3 in every 10 of the jobs fail with the error `Error: HttpError: Reference already exists`. I tried to change the check-out depth [as suggested](https://github.com/fjogeleit/yaml-update-action/issues/531#issuecomment-1326145969) in a similar issue(#531) but the issue still remains.
![image](https://user-images.githubusercontent.com/41787587/206163287-6436945c-3187-4f80-b4b6-64f7ea12078e.png)
Any help?

**Comment by 123MwanjeMike** [comment]
I did some bit of reading about the message and got that this error is  probably returned because responses from the GitHub api are being terminated prematurely. Do you think this is the case @fjogeleit?

**Comment by fjogeleit** [comment]
Can you provide some more details about your values?

Do you create a new branch / push in an existing one?

**Comment by 123MwanjeMike** [comment]
> Can you provide some more details about your values?
> 
> Do you create a new branch / push in an existing one?

I push to an existing branch. An example is below

```yaml
 - name: Update file
     uses: fjogeleit/yaml-update-action@main
     with:
          valueFile: "k8s/app6/values.yaml"
          propertyPath: "image.tag"
          value: ${{ env.imageTag }}
          branch: myBranch
          message: "Update app6 image tag to ${{ env.imageTag }}"
```

**Comment by fjogeleit** [comment]
Do you see an info log beforehand?

Something like `update branch ... failed (error message)`?

So as I expected, it fails to push to your branch and tries t o create them - which also failed. The error message from the logging above would be helpful to see the issue of updating your branch.

**Comment by 123MwanjeMike** [comment]
Oh yes, the full error message is:
`update branch myBranch failed (HttpError: Update is not a fast forward), fallback to create branch`

**Comment by fjogeleit** [comment]
https://help.github.com/articles/dealing-with-non-fast-forward-errors

I am not sure if I can help you without the knowledge of the full action and repo structructure.

Do you execute some other logic related to this repository / branch in your action which may cause this issue?

**Comment by 123MwanjeMike** [comment]
Not really, just the update. Below is the link to the exact usage:

https://github.com/123MwanjeMike/AirQo-api/blob/4d15652ee0bc9a7e3321815ae2b94d43bccd7d3b/.github/workflows/deploy-apis-to-staging.yml#L1117

**Comment by fjogeleit** [comment]
Hm I think the issue could be the multiple call of the action with commiting each time. Because the local copy is never updated the parent sha is each call t he same and the second pushes fails because it has the wrong parent sha and would overwrite the first push.

Possible solutions could be:

* Update the file in each step without commit/push the change and commiting / pushing everything together at the end
* Update your local branch after each update with a `git pull`
* Call the action only ones and using the `changes` input to update multiple values at once

If nothing of this works maybe a solution would be a new input that allows you to only commit each change and push them at the end but this has to be implemented.

**Comment by 123MwanjeMike** [comment]
Thanks @fjogeleit, let me try these solutions asap and share feedback

**Comment by fjogeleit** [comment]
Thanks for your feedback, I will have a look if I am able to implement something that could help.

**Comment by fjogeleit** [comment]
Unfortunately I found not way to update the branch via the JS SDK. Did you try to simple run `git pull` right before the failing action call?

**Comment by 123MwanjeMike** [comment]
Let me try the `git fetch` and share feedback

**Comment by 123MwanjeMike** [comment]
I've tried placing a `git fetch` before all the update steps and still had some jobs failing.

**Comment by 123MwanjeMike** [comment]
I was able to solve the issue using the [Wandalen/wretry.action](https://github.com/Wandalen/wretry.action) retry action on all the update all occurrences.
```yaml
      - name: Update file
        uses: Wandalen/wretry.action@master
        with:
          action: fjogeleit/yaml-update-action@main
          with: |
            valueFile: "k8s/app6/values.yaml"
            propertyPath: "image.tag"
            value: ${{ env.imageTag }}
            branch: myBranch
            message: "Update app6 image tag to ${{ env.imageTag }}"
```
