### ISSUE TITLE
Issue with noCompatMode and removing quotation marks

### ISSUE THREAD

**Issue by jorgepsmatos** [fjogeleit/yaml-update-action#535]
The following is my configuration

``` 
- name: Update Image Version in the related HelmChart values.yaml
  uses: fjogeleit/yaml-update-action@master
  with:
    valueFile: 'values.yaml'
    propertyPath: 'image.tag'
    value: ${{ steps.prep.outputs.tag }}
    branch: main
    masterBranchName: main
    createPR: false
    message: 'Update Image Version to ${{ steps.prep.outputs.tag }}'
    noCompatMode: true 
```

The value being replaced is: 

`nginx.ingress.kubernetes.io/proxy-buffering: "on"` into `nginx.ingress.kubernetes.io/proxy-buffering: on`

which breaks my application.

I tried both `noCompatMode: true` and `noCompatMode: false` and the value is replaced either way.
