### ISSUE TITLE
github action unable to pull integration

### ISSUE THREAD

**Issue by guy4boombox** [fjogeleit/yaml-update-action#539]
`
    - name: update values.yaml
      uses: fjogeleit/yaml-update-action@v0.12.3
     ... etc ...
`
results in 
   Error: HttpError: Resource not accessible by integration

**Comment by fjogeleit** [comment]
Ensure your GitHub token has the right permissions to execute the configurated operations.

Something I found with a quick search was:

```yaml
permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
```
