### ISSUE TITLE
Lexical error. Unrecognized text.

### ISSUE THREAD

**Issue by manisha-backbase** [fjogeleit/yaml-update-action#540]
Hi,
 I am getting this error ` Error: Error: Lexical error on line 1. Unrecognized text.
$.name-template
------^`  when I am trying to edit my yaml file

 ```
steps:
      - uses: actions/checkout@v3
      - uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: '.github/testing.yml'
          createPR: 'false'
          commitChange: false
          changes: |
            {
              "name-template": "testing123",
              "tag-template": "testing123",
              "tag-prefix": "testing123"
            }
```
            
YAML file
         
name-template: 'testing'
tag-template: 'testing'
tag-prefix: testing

**Comment by fjogeleit** [comment]
@manisha-backbase did you check if this syntax fixed your iassue?

**Comment by manisha-backbase** [comment]
This is the job 
generate-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fjogeleit/yaml-update-action@main
        with:
          createPR: 'false'
          commitChange: false
          branch: main
          masterBranchName: main
          changes: |
            {
              ".github/release-drafter-transfer.yml": {
                "['name-template']": "testing123",
                "['tag-template']": "testing123",
                "['tag-prefix']": "testing123"
              }
            }

**Comment by fjogeleit** [comment]
Hm okay, I think in your case you have to add the starting `$`.

```yaml
steps:
     - uses: actions/checkout@v3
     - uses: fjogeleit/yaml-update-action@main
       with:
         valueFile: '.github/testing.yml'
         createPR: 'false'
         commitChange: false
         changes: |
           {
             "$['name-template']": "testing123",
             "$['tag-template']": "testing123",
             "$['tag-prefix']": "testing123"
           }
```

Should work, this syntax worked in a local test
