### ISSUE TITLE
Q&A - How to update value of list of maps

### ISSUE THREAD

**Issue by wonderphil** [fjogeleit/yaml-update-action#546]
Hey mate,

Wondering if you could help out with a question, I am trying to update a value in list in a chart.yaml file and not sure how to do it and wonder if you could shed some light on it for me.

So the chart file looks like this:

```
apiVersion: v2
name: someservice
home: https://github.com/
version: 0.0.0
appVersion: 0.0.0
type: application
description: A Helm chart for services

dependencies:
  - name: ui
    repository: https://helm.repo.io
    version: 0.0.30
  - name: backend
    repository: https://helm.repo.io
    version: 0.0.1
  - name: someService
    repository: https://helm.repo.io
    version: 0.0.1
```

I want to just update the `version` of the dependencies `ui`, is this possible?

Thanks

Phil
