### ISSUE TITLE
 No changes to update detected

### ISSUE THREAD

**Issue by ahmedmoorsy** [fjogeleit/yaml-update-action#548]
Using the `yaml-update-action` show this error with these params, Any help ?
```
Run fjogeleit/yaml-update-action@v0.13.1
  with:
    propertyPath: spec.template.spec.containers[0].image
    value: docker-registry/project:rc--28cb528
    branch: test-28cb528
    targetBranch: master
    createPR: true
    message: Update Image Version to 28cb528
    token: ***
    workDir: cicd
    method: CreateOrUpdate
    noCompatMode: false
    quotingType: '
    masterBranchName: master
    githubAPI: https://api.github.com
    commitChange: true
    updateFile: false
    labels: yaml-updates
    commitUserName: github-actions[bot]
    commitUserEmail: **
Error: No changes to update detected
```

Code:
```
        uses: fjogeleit/yaml-update-action@v0.13.1
        with:
          valueFile: ${{ inputs.patch_file }}
          propertyPath: "spec.template.spec.containers[0].image"
          value: ${{ inputs.image-tag }}
          repository: ${{ inputs.e2e_gitops_repo }}
          branch: test-${{ inputs.commit-hash }}
          targetBranch: master
          createPR: true
          message: "Update Image Version to ${{ inputs.commit-hash }}"
          token: ${{ secrets.REPO_PAT }}
          workDir: cicd
```
