### ISSUE TITLE
Unable to change properties containing dashes. Lexical error.

### ISSUE THREAD

**Issue by ninoalloy** [fjogeleit/yaml-update-action#556]
Hello everyone!

We have used this neat GitHub action for a while within our team and it's worked really well.

A few days ago we noticed an issue with replacing a property within a YAML file, receiving the following error:  Lexical error on line 1. Unrecognized text.

The below picture shows the full error and file content acting on:

![image](https://github.com/fjogeleit/yaml-update-action/assets/41428989/bef11bfc-be9b-41f2-ac37-37d788b9873f)

Line 42 (missing from the screenshot) points clearly at the dash as the source of the lexical error.

The property name comes from external sources and we cannot change them. Trying to use the other ways in this GitHub action to specify changes leads to the same error.

We worked around the issue by using a different GitHub action so in case other people are needing a workaround here is the code used:
```
      - name: (Shared) Update Api Key
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.opentelemetry-collector.config.exporters.otlp.headers.api-key = "${{ secrets.NEW_RELIC_API_KEY }}"' 'Kubernetes/shared/values.yaml'
```

Please let me know if you need any other detail to help in torubleshooting the issue.
