### ISSUE TITLE
preverve dot notation without line breaks

### ISSUE THREAD

**Issue by oftoapp** [fjogeleit/yaml-update-action#566]
I have a yml like this:
```yaml
  ...
  set:
    backend.container.tag: "v1"
```
when I use action plugin. 

it replaces to like this:
```yaml
  ...
  set:
    backend.container.tag: "v1"
    backend:
      container:
        tag: "v1"
```
