### ISSUE TITLE
Insert a new entry in an array

### ISSUE THREAD

**Issue by MGaetan89** [fjogeleit/yaml-update-action#576]
I have a yaml file with looking as follow:
```yaml
a:
  b: 1
  c:
    - d: e
    - f: g
```

I'd like to end up with the following (ie. inserting a new entry at the beginning of `a.c`):
```yaml
a:
  b: 1
  c:
    - h: i
    - d: e
    - f: g
```

Is there a way to achieve that with this action?
