### ISSUE TITLE
Failed to create PR: Error: could not parse file with path

### ISSUE THREAD

**Issue by AndrzejOlender** [fjogeleit/yaml-update-action#577]
I have a parsing error, my yaml is in the form of a list and looks like this values-ci.yaml:

```
appContainers:
  - name: aaa-bbb
     image: eu.gcr.io/abc-test/aaa-bbb:gh-b5-argo
```
I tried setting the propertyPath below to the following values but I always get a parsing error.

`propertyPath: '.appContainers[0].image'
`
or
`propertyPath: 'appContainers.image'
`
failed to create PR: Error: could not parse file with path: /runner/_work/values-ci.yaml
How can I operate on this list here?

**Comment by fjogeleit** [comment]
your indentation looks wrong. image has to have the same indentation as name:

```yaml
appContainers:
  - name: aaa-bbb
     image: eu.gcr.io/abc-test/aaa-bbb:gh-b5-argo
```
