### ISSUE TITLE
No commits pushed to the branch

### ISSUE THREAD

**Issue by Poornachand200** [fjogeleit/yaml-update-action#581]
I need to update an YAML file path in existing branch and push the commits to the same branch. A new image version in the docker build has to updated everytime when the build runs which triggers a workflow.
It is not updating the image value. The valuepath seems correct. It says no commits to be pushed to the yaml file. Attached the log file of the actions.

```
      - name: Push app image
        id: image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "ciam-tdc-service"
          VERSION: "ciam-tdc-service-${{ github.sha }}"
        run: |
          IMAGE_ID=$REGISTRY/$REPOSITORY:dev-$VERSION
          echo "image_id=${IMAGE_ID}" >> "$GITHUB_OUTPUT"

      - name: Update Image Version in the kubernetes yaml file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev/ciam-tdc-service.yml'
          propertyPath: 'spec.template.spec.containers.0.image'
          value: ${{ steps.image.outputs.image_id }}
          repository: nuuday/ciam-tdc-service
          branch: ${{ github.head_ref }}
          commitChange: true
          force: true
          message: 'Update Image Version to ${{ steps.image.outputs.image_id }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          workDir: k8s
```

YAML file

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ciam-test
  name: ciam-tdc-service
  annotations:
    application_service: "TDC-service"
    spoc: "Poornachand - poos@nuuday.dk"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciam-tdc-service
  template:
    metadata:
      labels:
        app: ciam-tdc-service
      annotations:
        application_service: "TDC-service"
        spoc: "Poornachand - poos@nuuday.dk"
    spec:
      serviceAccountName: ciam-tdc-service
      containers:
        - name: ciam-tdc-service
          image: 435576480396.dkr.ecr.eu-north-1.amazonaws.com/ciam-tdc-service:ciam-tdc-service-8937807a52abc4de29cff954af49a4091fd09975
          imagePullPolicy: Always
          ports:
            - name: https
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"              
---

```
[logs_25667998407.zip](https://github.com/user-attachments/files/16107364/logs_25667998407.zip)

**Comment by fjogeleit** [comment]
If I see it correctly you have multiple definitions in a single YAML file. In this case you need to specify the item you want to change:

```yaml
      - name: Update Image Version in the kubernetes yaml file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev/ciam-tdc-service.yml'
          propertyPath: '[0].spec.template.spec.containers[0].image'
```

You can see within your logs if the value was change as expected.

**Comment by Poornachand200** [comment]
Now the yaml file and property path is updated as below. Its the same error again.
[logs_25672991444.zip](https://github.com/user-attachments/files/16108617/logs_25672991444.zip)


```
      - name: Update Image Version in the kubernetes yaml file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev/ciam-tdc-service.yml'
          propertyPath: 'spec.template.spec.containers.0.image'
          value: ${{ steps.image.outputs.image_id }}
          repository: nuuday/ciam-tdc-service
          branch: ${{ github.head_ref }}
          commitChange: true
          force: true
          message: 'Update Image Version to ${{ steps.image.outputs.image_id }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          workDir: k8s
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ciam-dev
  name: ciam-tdc-service
  annotations:
    application_service: "TDC-service"
    spoc: "Poornachand - poos@nuuday.dk"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciam-tdc-service
  template:
    metadata:
      labels:
        app: ciam-tdc-service
      annotations:
        application_service: "TDC-service"
        spoc: "Poornachand - poos@nuuday.dk"
    spec:
      serviceAccountName: ciam-tdc-service
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: ciam-tdc-service
          image: 435576480396.dkr.ecr.eu-north-1.amazonaws.com/ciam-tdc-service:dev-ciam-tdc-service-8567691bde992e0ddcf26b365f2c84870db11c2f
          imagePullPolicy: Always
          ports:
            - name: https
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
```

**Comment by fjogeleit** [comment]
Your error is a different one: `failed to create PR: HttpError: Not Found`. Its a bit missleading at this point because you dont create a PR but: `HttpError: Not Found` is the GitHub API Error you get by try to commit your change.

This means most likely that your token has not all permissions to perform this action.

You can try to add to give your token the necessary permissions:

```yaml
permissions:
  contents: write
```

**Comment by Poornachand200** [comment]
I have added all the permissions now. The error is failed to create PR: HttpError: Not Found .  I also set createPR to false.
```

permissions:
  id-token: write
  contents: write
  checks: write
  issues: write
  packages: write
  pull-requests: write

- name: Update Image Version in the kubernetes yaml file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev/ciam-tdc-service.yml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: ${{ steps.image.outputs.image_id }}
          repository: nuuday/ciam-tdc-service
          branch: ${{ github.head_ref }}
          commitChange: true
          createPR: false
          force: true
          message: 'Update Image Version to ${{ steps.image.outputs.image_id }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          workDir: k8s
```
[logs_25675719649.zip](https://github.com/user-attachments/files/16109450/logs_25675719649.zip)

**Comment by fjogeleit** [comment]
Yes, as mentioned is the `failed to create PR` part misleading and not true in this case, I need to improve the custom message.

On thing I just realized. You did not set the `targetBranch` which is `master` by default. You need to set it to the branch you want to update.

**Comment by Poornachand200** [comment]
targetBranch is set now. I also tried passing a custom token with all required permission. I ended up with `failed to create PR: HttpError: Not Found`

```

      - name: Update Image Version in the kubernetes yaml file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev/ciam-tdc-service.yml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: ${{ steps.image.outputs.image_id }}
          repository: nuuday/ciam-tdc-service
          branch: ${{ github.head_ref }}
          commitChange: true
          createPR: false
          targetBranch: ${{ github.head_ref }}
          force: true
          message: 'Update Image Version to ${{ steps.image.outputs.image_id }}'
          token: ${{ secrets.PAT_TOKEN }}
          workDir: k8s
```

**Comment by fjogeleit** [comment]
What is your trigger of this action? Is it a PR? Otherwise head_ref is not available, your logs showing that it resolves to an empty string.

**Comment by Poornachand200** [comment]
Yes, the head_ref was empty. Now the worklow is updated as below and the build runs green. But the commits are not actual pushed to the branch. It seems it is not verified. Please refer the image 

<img width="934" alt="image" src="https://github.com/fjogeleit/yaml-update-action/assets/147699215/ef7cd8d0-d4e0-475c-9add-288450ee889c">


```
name: Build and run tests for dev

on:
  workflow_dispatch:
  push:
    branches:
      - "feature/**"
    paths:
      - "src/main"

permissions:
  id-token: write
  contents: write
  checks: write
  issues: write
  packages: write
  pull-requests: write

jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' 
          java-version: '21'
          cache: "gradle"
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
    
      - name: Build with Gradle
        run: ./gradlew build

      - name: list inside build folder
        run:  |
          ls -lsa build     
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_SECRETS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build
        env:
          DOCKERFILE: "./Dockerfile.jvm"
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "ciam-tdc-service"
          VERSION: "ciam-tdc-service-${{ github.sha }}"
        run: docker buildx build --platform linux/amd64 -f $DOCKERFILE -t $REGISTRY/$REPOSITORY:dev-$VERSION .

      - name: Push
        env:
          DOCKERFILE: "./Dockerfile.jvm"
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "ciam-tdc-service"
          VERSION: "ciam-tdc-service-${{ github.sha }}"
        run: docker buildx build --push --platform linux/amd64 -f $DOCKERFILE -t $REGISTRY/$REPOSITORY:dev-$VERSION .
      
      - name: Push app image
        id: image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "ciam-tdc-service"
          VERSION: "ciam-tdc-service-${{ github.sha }}"
        run: |
          IMAGE_ID=$REGISTRY/$REPOSITORY:dev-$VERSION
          echo "image_id=${IMAGE_ID}" >> "$GITHUB_OUTPUT"

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Update Image Version in the kubernetes yaml file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev/ciam-tdc-service.yml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: ${{ steps.image.outputs.image_id }}
          repository: nuuday/ciam-tdc-service
          branch: ${{ steps.extract_branch.outputs.branch }}
          commitChange: true
          createPR: false
          targetBranch: ${{ steps.extract_branch.outputs.branch }}
          force: true
          message: 'Update Image Version to ${{ steps.image.outputs.image_id }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          workDir: k8s
```

**Comment by Poornachand200** [comment]
Attached the log of the previous comment
[logs_25680481170 (1).zip](https://github.com/user-attachments/files/16110853/logs_25680481170.1.zip)

**Comment by fjogeleit** [comment]
What do you mean? In your screen I see the commit with the message you defined and also in your log you see the created commit hash: d3e1e97430ad17c3876c9b201f789d8482d7d62d

**Comment by Poornachand200** [comment]
But the commit doesn't seem like pushed to the branch feature/pf-changes. targetbranch and branch names are pointed to feature/pf-changes. Branch is not updated with the commit.

**Comment by fjogeleit** [comment]
Your screen is showing the created commit in the branch and there are no errors in the logs. So I don’t your issue. Is the expected change not in the created commit?

**Comment by Poornachand200** [comment]
Yes, the expected change is not the commit. commit shah is still the old 8567691bde992e0ddcf26b365f2c84870db11c2f and I don't see the expected change in the branch

**Comment by fjogeleit** [comment]
Not sure if this could be a reason but you should not use k8s as workDir, it should be the dir where you checked out the whole project. So basically the base workdir. Add k8s to the valueFile path

**Comment by Poornachand200** [comment]
Yes, that was the issue. The commits are getting updated correctly. Thanks for the prompt responses.

**Comment by Poornachand200** [comment]
This time I am creating a PR instead of directly updating the branch. But I am encountering http error. Atatched the complete log file.  Revert changes 
Error: failed to create PR: HttpError: Not Found
[logs_26102196416.zip](https://github.com/user-attachments/files/16265233/logs_26102196416.zip)

```
name: Build and run tests for prod

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'k8s/**'
      - '.github/**'

permissions:
  id-token: write
  contents: write
  checks: write
  issues: write
  packages: write
  pull-requests: write

jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' 
          java-version: '21'
          cache: "gradle"
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
    
      - name: Build with Gradle
        run: ./gradlew build

      - name: list inside build folder
        run:  |
          ls -lsa build     
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_SECRETS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build
        env:
          DOCKERFILE: "./Dockerfile.jvm"
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "ciam-sync-service"
          VERSION: "ciam-sync-service-${{ github.sha }}"
        run: docker buildx build --platform linux/amd64 -f $DOCKERFILE -t $REGISTRY/$REPOSITORY:prod-$VERSION .

      - name: Push
        env:
          DOCKERFILE: "./Dockerfile.jvm"
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "ciam-sync-service"
          VERSION: "ciam-sync-service-${{ github.sha }}"
        run: docker buildx build --push --platform linux/amd64 -f $DOCKERFILE -t $REGISTRY/$REPOSITORY:prod-$VERSION .

      - name: Get Image URI
        id: image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "ciam-sync-service"
          VERSION: "ciam-sync-service-${{ github.sha }}"
        run: |
          IMAGE_ID=$REGISTRY/$REPOSITORY:prod-$VERSION
          echo "image_id=${IMAGE_ID}" >> "$GITHUB_OUTPUT"

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Update Image Version in the kubernetes yaml file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'k8s/production/ciam-sync-service.yml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: ${{ steps.image.outputs.image_id }}
          repository: nuuday/ciam-sync-service
          branch: image-${{ github.sha }}          
          commitChange: true
          createPR: true
          targetBranch: ${{ steps.extract_branch.outputs.branch }}
          force: true
          message: 'Update Image Version to ${{ steps.image.outputs.image_id }}'
          token: ${{ secrets.GITHUB_TOKEN }}
```

This works:

```

      - name: Update Image Version in the kubernetes yaml file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'k8s/production/ciam-sync-service.yml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: ${{ steps.image.outputs.image_id }}
          repository: nuuday/ciam-sync-service
          branch: ${{ steps.extract_branch.outputs.branch }}
          commitChange: true
          createPR: false
          targetBranch: ${{ steps.extract_branch.outputs.branch }}
          force: true
          message: 'Update Image Version to ${{ steps.image.outputs.image_id }}'
          token: ${{ secrets.GITHUB_TOKEN }}
```
