### ISSUE TITLE
action doesn't open a PR

### ISSUE THREAD

**Issue by yalattas** [fjogeleit/yaml-update-action#592]
```
- name: Update values.yaml
    uses: fjogeleit/yaml-update-action@main
    with:
      repository: ${{ inputs.repository }}
      description: "deploying changes on repository *${{ inputs.repository }}* from *${{ inputs.source-branch }}* to *${{ inputs.target-branch }}* image URI: *${{ inputs.image-uri }}"
      valueFile: ${{ inputs.file-path }}
      branch: ${{ inputs.source-branch }}
      targetBranch: ${{ inputs.target-branch }}
      commitChange: ${{ inputs.commit-change }}
      message: "[bot] deploy image to cluster as a preview environment"
      masterBranchName: ${{ inputs.master-branch-name }}
      token: ${{ inputs.token }}
      commitUserName: APP CI
      commitUserEmail: app.ci@users.noreply.github.com
      workDir: ${{ inputs.work-directory }}
      createPR: 'true'
      changes: ${{ inputs.changes }}
      labels: ${{ inputs.labels }}
      force: 'true'
```
for some reason. This is causing the action to commit directly to targetBranch and doesn't open a PR at all. Even with force

Another issue is JSON parser when we want to create extra attributes in yaml

The rationale behind it is to use GitOps methodology to create PR and then provisioning preview environment. Hence, we need to change existing values in YAML + creating new values special for preview environment in the same YAML

**Comment by yalattas** [comment]
values passed to composite action as follows
```
with:
          image-uri: ${{ secrets.IMAGE_URI }}/ORGANIZATION:ci-inf-00-support-preview-environment
          repository: ORGANIZATION/gitops
          work-directory: infrastructure
          file-path: clusters/ORG-dev/apps/ORG-core/values.yaml
          source-branch: ${{ github.head_ref }}
          target-branch: main
          commit-change: 'true'
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          changes: |
            {
              "ORG.apps.backend.hpa.enabled": false
            }
````

keep in mind that `head_ref` doesn't exist in GitOps repo and should be created by this action. If not, Then we need to create. Yet, we're not sure
