### ISSUE TITLE
support changing keys in YAML

### ISSUE THREAD

**Issue by yalattas** [fjogeleit/yaml-update-action#593]
some values depends on dynamic keys to be rendered by helm template

example
```
cluster:
    cluster1:
        enabled: false
    cluster2:
        enabled: true
```

where `cluster1` and `cluster2` provided by the user

Hence, an ability to change the keys or dynamically construct an object is valuable to update YAML file

example
```
changes: |
            {
              "APP.apps.backend.hpa.enabled": false,
              "APP.apps.backend.image": "${{ secrets.IMAGE_URI }}/APP:ci-inf-00-support-preview-environment",
              "APP.apps.backend.replicas": 1,
              "APP.apps.backend.serviceAccount.name": "ci-inf-00-support-preview-environment",
              "APP.apps.backend.prometheusRule.enabled": false,
              "APP.apps.backend.DYNAMIC_KEY": {
                "enabled": true
              }
            }
```

**Comment by yalattas** [comment]
another issue if the key has dots in it
for example
```
APP.apps.backend.'example.com'": "something"
```
in YAML
```YAML
APP:
  apps:
    backend:
      example.com: something
```
Yet, the action expects dots as object anchor. We tried `backend.example\.com`, `backend.example\\.com`, `backend.'example.com'` with no luck yet
