### ISSUE TITLE
Pull Request (PR) is not being created.

### ISSUE THREAD

**Issue by sushmitha-15** [fjogeleit/yaml-update-action#594]
Pull Request (PR) is not being created. 
Below is the log file:
```
Run fjogeleit/yaml-update-action@v0.16.0
  with:
    valueFile: deployment/kubernetes/helm/charts/frontend/values-dev.yaml
    propertyPath: appFrontend.image.tag
    value: 1660
    branch: dev-image-version-update
    targetBranch: dev
    createPR: true
    commitChange: false
    message: Update Image Version to 1660
    githubAPI: https://git.i.mercedes-benz.com/api/v3
    token: ***
    noCompatMode: false
    quotingType: '
    force: false
    masterBranchName: master
    updateFile: false
    labels: yaml-updates
    repository: DNA/NeuDnAPlatform
    workDir: .
    commitUserName: github-actions[bot]
    commitUserEmail: 41898[2](https://git.i.mercedes-benz.com/DNA/NeuDnAPlatform/actions/runs/13829375/job/48221047#step:4:2)82+github-actions[bot]@users.noreply.github.com
  env:
    REGISTRY: registry-emea.app.corpintra.net
    REGISTRY_DNA_USER: robot_dnaplatform+cicdbot
    NO_PROXY: 
    RUNNER_ALLOW_RUNASROOT: 1
    BLACKDUCK_URL: https://bdscan.i.mercedes-benz.com/
    SECHUB_USERID: pid6c[3](https://git.i.mercedes-benz.com/DNA/NeuDnAPlatform/actions/runs/13829375/job/48221047#step:4:3)9
    SECHUB_SERVER: https://sechub.app.corpintra.net
```
Below code is in the YAML file:

```
  development:
    name: 'Deploy to Development'
    needs: build
    if: ${{ github.ref_name == 'dev' || inputs.ENVIRONMENT == 'Development' }}
    runs-on: [os-medium-amd64-linux]
    environment:
      name: Development
    steps:

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        ref: 'dev'       

    - name: Update Image Version values.yaml
      uses: fjogeleit/yaml-update-action@v0.16.0
      id: cpr
      with:
        valueFile: ${{ inputs.HELM_FOLDER }}/values-dev.yaml
        propertyPath: '${{ inputs.YML_IMAGE_TAG_PATH }}'
        value: ${{ github.run_number }}
        branch: dev-image-version-update
        targetBranch: dev
        createPR: true
        commitChange: false
        message: 'Update Image Version to ${{ github.run_number }}' 
        githubAPI: https://git.i.mercedes-benz.com/api/v3
        token: ${{ secrets.PID_PAT }}
```

Added the permissions as well:
```
permissions:                    
  contents: write
  pull-requests: write 
```

**Comment by fjogeleit** [comment]
Hey, can you try to set `commitChange` to `true`?

**Comment by sushmitha-15** [comment]
yes, when I set commitChange to true, it giving the below error:
Error: failed to create PR: HttpError: Not Found
```

Run fjogeleit/yaml-update-action@v0.16.0
  with:
    valueFile: deployment/kubernetes/helm/charts/frontend/values-dev.yaml
    propertyPath: appFrontend.image.tag
    value: 1659
    branch: dev-image-version-update
    targetBranch: dev
    createPR: true
    commitChange: true
    message: Update Image Version to 1659
    githubAPI: https://git.i.mercedes-benz.com/api/v3
    token: ***
    noCompatMode: false
    quotingType: '
    force: false
    masterBranchName: master
    updateFile: false
    labels: yaml-updates
    repository: DNA/NeuDnAPlatform
    workDir: .
    commitUserName: github-actions[bot]
    commitUserEmail: 41898[2](https://git.i.mercedes-benz.com/DNA/NeuDnAPlatform/actions/runs/13827664/job/48215914#step:4:2)82+github-actions[bot]@users.noreply.github.com
  env:
    REGISTRY: registry-emea.app.corpintra.net
    REGISTRY_DNA_USER: robot_dnaplatform+cicdbot
    NO_PROXY: 
    RUNNER_ALLOW_RUNASROOT: 1
    BLACKDUCK_URL: https://bdscan.i.mercedes-benz.com/
    SECHUB_USERID: pid6c[3](https://git.i.mercedes-benz.com/DNA/NeuDnAPlatform/actions/runs/13827664/job/48215914#step:4:3)9
    SECHUB_SERVER: https://sechub.app.corpintra.net
Error: failed to create PR: HttpError: Not Found
```

**Comment by sushmitha-15** [comment]
I am creating a pull request for the same repository

**Comment by fjogeleit** [comment]
Sorry for the late response, I was on a conference and had not much time.

It looks like you setting your own token, so the permissions section has no effect. I would suggest to remove your custom token and use the generated one with the permissions you set.

**Comment by sushmitha-15** [comment]
Tried using the githubtoken:

```
    - name: Update Image Version values.yaml
      uses: fjogeleit/yaml-update-action@v0.16.0
      id: cpr
      with:
        valueFile: ${{ inputs.HELM_FOLDER }}/values-dev.yaml
        propertyPath: '${{ inputs.YML_IMAGE_TAG_PATH }}'
        value: ${{ github.run_number }}
        branch: dev-image-version-update
        targetBranch: dev
        createPR: true
        commitChange: true
        message: 'Update Image Version to ${{ github.run_number }}' 
        githubAPI: https://git.i.mercedes-benz.com/api/v3
        token: ${{ secrets.GITHUB_TOKEN }}
```

Got that same error: Error: failed to create PR: HttpError: Not Found
