### ISSUE TITLE
failed to create PR: HttpError: Not Found

### ISSUE THREAD

**Issue by siddheshengineer** [fjogeleit/yaml-update-action#595]
Can someone please let me know what I am doing wrong here? so when using fjogeleit/yaml-update-action@main with commitChange: true and createPR: false ( I want to update the branch directly)

, the action incorrectly attempts to create a pull request, resulting in the error failed to create PR: HttpError: Not Found, even though the configuration is intended to commit changes directly to the current branch. 

This is my configuration:
```
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          valueFile: {path}-helmcharts/values.yaml
          propertyPath: '${{ needs.build_container_images.outputs.service }}' # <- coming from previous step
          value: ${{ needs.build_container_images.outputs.image_tag }}  # <- coming from previous step
          commitChange: true
          message: '${{ needs.build_container_images.outputs.service }} values updated to ${{ github.run_number }}'  # <- coming from previous step
          createPR: false
          token: ${{ secrets.GITHUB_TOKEN }}
```

Workflow output: 
![Image](https://github.com/user-attachments/assets/0718349e-198b-4b26-a76f-e4e01f838391)

**Comment by fjogeleit** [comment]
Hey, it did not try to create a PR. The error message was wrong at this point. I fixed the code with v0.16.1 to fix that message. Its most likely break by pushing the change.

Do you try to commit in the same repo as the action runs or a different one?

**Comment by siddheshengineer** [comment]
Hey thanks for messages, yes, it's trying to update the same repo.

**Comment by fjogeleit** [comment]
Do you Grant content Write permissions?
```yaml
permissions:
  content: write
```

**Comment by siddheshengineer** [comment]
Ahh, thanks for this, I accident left it on read permission, I corrected it and used v0.16.1

```
    permissions:
      contents: write # required to commit to branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@v0.16.1
        with:
          valueFile: astronomy-helmcharts/values.yaml
          propertyPath: '${{ needs.build_container_images.outputs.service }}'
          value: ${{ needs.build_container_images.outputs.image_tag }}
          commitChange: true
          message: '${{ needs.build_container_images.outputs.service }} values updated to ${{ github.run_number }}'
          createPR: false
          token: ${{ secrets.GITHUB_TOKEN }}
```

Got this updated error, just for conetxt my branch is not master branch, is that causing the issue? because the action expects master as branch name? : 

![Image](https://github.com/user-attachments/assets/808d6779-26df-4d81-96fa-513d33ce7514)
